Layout/AlignArguments:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentAssignment:
  Enabled: false

Layout/IndentFirstArgument:
  Enabled: false

Layout/IndentFirstArrayElement:
  Enabled: false

Layout/IndentFirstHashElement:
  Enabled: false

Layout/IndentFirstParameter:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/LeadingBlankLines:
  Enabled: false
