inherit_from:
  - .ruby-style.yml

require:
  - rubocop-performance
  - rubocop-rspec

Layout/AlignArguments:
  Enabled: false

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: true

Layout/IndentArray:
  Enabled: true

Layout/SpaceAroundOperators:
  MultiSpaceAllowedForOperators: false
  
Performance/Count:
  SafeMode: true

Lint/SafeNavigationConsistency:
  Whitelist: presence

Style/SwapValues:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/RescueException:
  ErrorName: RuntimeError
