---
Layout/SpaceAroundOperators:
  MultiSpaceAllowedForOperators: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: true
Layout/HashAlignment:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
Layout/FirstArrayElementIndentation:
  Enabled: true
