---
require:
- rubocop-performance
- rubocop-rspec
Layout/SpaceAroundOperators:
  Enabled: true
Lint/SafeNavigationConsistency:
  AllowedMethods: presence
Style/SwapValues:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/RescueException:
  ErrorName: RuntimeError
Lint/UselessAssignment:
  FixType: Test
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: true
Layout/HashAlignment:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
Layout/FirstArrayElementIndentation:
  Enabled: true
