DeepSource/BadOrAssignment:
  Enabled: true

DeepSource/BinaryExpressionOperandOrder:
  Enabled: true

DeepSource/DuplicateConstantAssignment:
  Enabled: true

DeepSource/ExcessiveGuardClauses:
  Enabled: true

DeepSource/IoSelectWithSingleArgument:
  Enabled: true
