Layout/AlignArguments:
  Enabled: false

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: true

Layout/IndentArray:
  Enabled: true

Layout/SpaceAroundOperators:
  MultiSpaceAllowedForOperators: false
  
Performance/Count:
  SafeMode: true

Lint/SafeNavigationConsistency:
    Whitelist: presence
