inherit_from:
- 'https://shopify.github.io/ruby-style-guide/rubocop.yml'
- .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

Layout/AlignArguments:
  Enabled: false

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: true

Layout/IndentArray:
  Enabled: true

Layout/SpaceAroundOperators:
  MultiSpaceAllowedForOperators: false
  
Performance/Count:
  SafeMode: true

Lint/SafeNavigationConsistency:
  Whitelist: presence

Style/SwapValues:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/RescueException:
  ErrorName: RuntimeError

Lint/UselessAssignment:
  FixType: Test
